### ISSUE TITLE
option to skip gembs_tasks.json?

### ISSUE THREAD

**Issue by MareikeJaniak** [heathsc/gemBS-rs#14]
Hi Simon,

I'm interested in incorporating gemBS-rs into the methylation sequencing protocol of our genomics pipeline (GenPipes: https://bitbucket.org/mugqic/genpipes/src/master/). Our pipeline already does a lot of the handling and parallelization of tasks for multiple samples, and keeps track of which tasks have been successfully executed. In this context, some of the tracking capabilities of gemBS-rs are causing a bit of a headache and we were wondering if it's possible to skip the creation of the .gembs_tasks.json, for example.

The issue with the .gembs_tasks.json that gemBS creates to keep track of the different tasks is the lock system to prevent multiple processes writing to the tasks at the same time. Our pipeline creates and submits job scripts for both PBS and SLURM schedulers, which are then run in parallel for all samples in a project. I'm seeing a lot that processes are delayed/time out because they can't write to the locked file. Often, if a sample fails for whatever reason, its lock isn't removed, for example, so all other samples time out. Restarts of our pipeline also don't work as expected if the .gembs_tasks.json lists the process that is meant to restart.

Happy to provide more details on how we've incorporated the gemBS-rs functions so far, but for now, it would be useful to know if the .gembs_tasks.json can be skipped or, alternatively, if it's possible to rename it to create a separate .json for each sample? (By sample, I mean what is referred to as 'barcode' in the metadata.)

Best, 
Mareike

**Comment by heathsc** [comment]
Hi Mareike,

There's no simple way of turning off the creation of the gembs_tasks.json.
However, you can change the working directory where gemBS looks for the
configuration files (-d option) and creates the gembs_tasks.json and lock
file.  Could you set up the tasks so that they each use a different working
directory?  You would need to have a master working directory (which would
normally be .gemBS/) where the config file (gemBS.mp) is located, and then
copy or link the config file to the task specific working directory.

Simon

**Comment by MareikeJaniak** [comment]
Hi Simon, 

Thanks for the quick response! The -d option sounds like what I was looking for, perfect. I will give that a try. 

Best, 
Mareike

**Comment by MareikeJaniak** [comment]
Hi Simon, 

Just wanted to send an update that this solution is working well so far! 
Within the pipeline, we first generate a master gemBS.mp file and then copy that to individual working directories for each sample, before calling gemBS with the --dir option, pointing to the individual working directories. 

Best, 
Mareike
