### ISSUE TITLE
Mapping as non-stranded not recognized in gem-mapper

### ISSUE THREAD

**Issue by cbreenmachine** [heathsc/gemBS-rs#2]
Hi Simon,

I am trying to use the gemBS pipeline to process some whole human genome bisulfite sequence data that is single-ended. Specifically, I am trying to run the mapping command with non-stranded reads. The command I am using is `gemBS map --read-non-stranded`. However, it is unable to run and produces the following information within a few seconds. For what it's worth, I can run `gemBS run` on the demo dataset provided in the documentation for gemBS version 3 [here](http://statgen.cnag.cat/gemBS/v3/UserGuide/_build/html/example.html).

**Logfile**
>The logfile gives the following information:
(base) bash-4.2$ cat single_map_sample001_101.log 
/ua/cebreen/lib/gemBS/bin/gem-mapper: unrecognized option '--bisulfite-conversion non-stranded'
GEM-Mapper error:
> Option not recognized
samtools sort: failed to read header from "-"`

**Condensed terminal output (when running in debug mode)**
>INFO - Launch:
        /ua/cebreen/lib/gemBS/bin/gem-mapper --threads 4 -I ./../index/GRCh38.primary_assembly.BS.gem -i ./fastq_trimmed/sample001_101/sample001_101_L001_R1_trimmed.fq --bisulfite-conversion non-stranded --report-file ./mapping/sample001_101.json --sam-read-group-header @RG\tID:sample001_101\tSM:\tBC:sample001_101\tPU:sample001_101 | /ua/cebreen/lib/gemBS/bin/read_filter ./../index/GRCh38.primary_assembly.gemBS.contig_md5 | /ua/cebreen/lib/gemBS/bin/samtools sort -o ./mapping/sample001_101.bam -T ./mapping --threads 4 --write-index -
DEBUG - Try to remove output file ./mapping/sample001_101.bam
DEBUG - Try to remove output file ./mapping/sample001_101.json
DEBUG - Try to remove output file ./mapping/sample001_101.bam.csi
DEBUG - Worker thread 7 shutting down after error Error from pipeline: /ua/cebreen/lib/gemBS/bin/samtools exited with error
ERROR - Error received from worker thread 7
DEBUG - Job loop finished - cleaning up
ERROR - Worker thread 4 received error: receiving on a closed channel
ERROR - Worker thread 2 received error: receiving on a closed channel
DEBUG - Worker thread 2 shutting down
DEBUG - Worker thread 4 shutting down
ERROR - Worker thread 5 received error: receiving on a closed channel
DEBUG - Worker thread 5 shutting down
ERROR - Worker thread 1 received error: receiving on a closed channel
DEBUG - Worker thread 1 shutting down
ERROR - Worker thread 3 received error: receiving on a closed channel
DEBUG - Worker thread 3 shutting down
ERROR - Worker thread 6 received error: receiving on a closed channel
DEBUG - Worker thread 6 shutting down
ERROR - Worker thread 0 received error: receiving on a closed channel
DEBUG - Worker thread 0 shutting down
Error: "Exiting after error"

Is there anything glaringly obvious I'm messing up? I will continue to try to find the source of the error or at least more information! Please let me know if I can provide anything specific that would help.
Thanks in advance!

Best,
Coleman

**Comment by heathsc** [comment]
Thank you for the report - this was a previously unreported bug that I have now fixed and pushed to the repo (just a typo).  I will remake the Singularity and docker containers, but this will take a few hours. 

Cheers,
Simon

**Comment by cbreenmachine** [comment]
Thanks so much Simon! That's great!

Best,
Coleman
